### ISSUE TITLE
Unable to access jarfile CSGOCaseStatsViewerV2-1.0.3-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by Fixxzle** [cantryDev/CSGOCaseStatsViewerV2#9]
Hi cantryDev,
Trying to use this tool and getting this error. I am running Java 20 any thoughts?
![image](https://github.com/cantryDev/CSGOCaseStatsViewerV2/assets/47392470/e5a73d28-7b9f-4cde-95d9-f35a4605337e)

**Comment by Fixxzle** [comment]
![image](https://github.com/cantryDev/CSGOCaseStatsViewerV2/assets/47392470/0d3b716e-2b4a-4d9c-aab3-f3445af60ca6)
defaults for jars are set

**Comment by Toplit** [comment]
It's missing the jar file for some reason - I had the same issue and solved it by downloading an earlier release and copying the jar file into root. 

Download I used: https://github.com/cantryDev/CSGOCaseStatsViewerV2/files/11793480/CSGOCaseStatsViewerV2-1.0.2.zip

**Comment by n0eL1405** [comment]
Judging by the folder seen in the console you downloaded the source code that does not contains a compiled jar file (I assume this because of the "-master" at the end wich means you downloaded the source code of the master branch).  
Either you compile the jar by your self or you download the latest compiled jar as described [here in the _Usage_ section](https://github.com/cantryDev/CSGOCaseStatsViewerV2#usage)

**Comment by cantryDev** [comment]
If this error comes it mean you downloaded the wrong files.
Follow the steps one by one: https://github.com/cantryDev/CSGOCaseStatsViewerV2#usage
